// <auto-generated />
using System;
using Consorcio_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consorcio_Api.Migrations
{
    [DbContext(typeof(DbemployeesContext))]
    [Migration("20230909204340_mssql_migration_749")]
    partial class mssql_migration_749
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consorcio_Api.Models.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartment"));

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdDepartment")
                        .HasName("PK__Departme__DF1E6E4BC4AB4F85");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("Consorcio_Api.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<DateTime?>("ContractDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("contract_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Full_name");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("int");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("IdEmployee")
                        .HasName("PK__Employee__51C8DD7A4193F9AD");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Consorcio_Api.Models.Employee", b =>
                {
                    b.HasOne("Consorcio_Api.Models.Department", "IdDepartmentNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("IdDepartment")
                        .HasConstraintName("FK__Employee__IdDepa__3A81B327");

                    b.Navigation("IdDepartmentNavigation");
                });

            modelBuilder.Entity("Consorcio_Api.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
